[package]
name = "jester_algebra_derive"
version = "0.1.0"
authors = ["Cydhra <ubezl@student.kit.edu>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.5"
quote = "1.0.2"
num = "0.2.0"
num-bigint = { version = "0.2.3", features = ["rand"]}
