[package]
name = "jester_sharing_proc"
version = "0.1.0"
authors = ["Cydhra <ubezl@student.kit.edu>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.7"
syn = { version = "1.0.13", features = ["full"] }
quote = "1.0.2"