[package]
name = "jester_hashes"
version = "0.1.0"
authors = ["Cydhra <ubezl@student.kit.edu>"]
edition = "2018"

[dependencies]
jester_util = { path = "../jester_util" }

[dev-dependencies]
hex = "0.3.2"