//! This module defines trait for different sharing schemes and provides some default implementations for those.

use crate::{CryptoRng, RngCore};

pub mod shamir_secret_sharing;

/// A threshold secret sharing scheme that generates n shares of a given secret and requires t <= n of those shares
/// to reconstruct the secret. The secret is of type `T` and shares are a `Vec<S>`.
///
/// # Type Parameters
/// - `T` type of secrets that can be shared using this scheme
/// - `S` type of shares generated by this scheme
pub trait ThresholdSecretSharingScheme<T, S> {
    /// Generate shares of a secret demanding that at least `threshold` shares must be available to reconstruct the
    /// secret.
    ///
    /// # Parameters:
    /// - `rng` a cryptographically secure random number generator.
    /// - `secret` an instance of `T`
    /// - `count` how many shares to generate
    /// - `threshold` how many shares are required to reconstruct the secret
    ///
    /// # Returns
    /// Returns a vector of `count` shares if the `secret`
    fn generate_shares<R>(rng: &mut R, secret: &T, count: usize, threshold: usize) -> Vec<S>
    where
        R: RngCore + CryptoRng;

    /// Take a vector of shares and reconstruct the secret from them. At least `threshold` shares must be present,
    /// otherwise the secret cannot be reconstructed
    /// # Parameters
    /// - `shares` a collection of at least `threshold` shares
    /// - `threshold` the original threshold the shares were generated upon. This may be less than the actual number
    /// of shares given, but it must be the same value as during generation
    ///
    /// # Returns
    /// Given that `threshold` matches the threshold at generation and enough shares are present, it will return an
    /// instance of `T` that is the secret reconstructed from the shares
    fn reconstruct_secret(shares: &[S], threshold: usize) -> T;
}

/// A trait for sharing schemes whose shares addition is linear thus enabling the addition of shares of this
/// scheme without further protocol state required.
pub trait LinearSharingScheme<T, S> {
    /// Sum two shares resulting in a new share of their secrets' sum.
    fn add_shares(lhs: &S, rhs: &S) -> S;

    /// Subtract `rhs` from `lhs` resulting in a new share of their secrets' difference.
    fn sub_shares(lhs: &S, rhs: &S) -> S;

    /// Add a scalar of the field `T` to the `share`
    fn add_scalar(share: &S, scalar: &T) -> S;

    /// Subtract a scalar of the field `T` from the `share`
    fn sub_scalar(share: &S, scalar: &T) -> S;

    /// Multiply a `share` that is defined over the field `T` with a `scalar` from `T`.
    fn multiply_scalar(share: &S, scalar: &T) -> S;

    /// Sum a slice of shares resulting in a `Some` with a new share of their secrets' sum or `None` if the slice was
    /// empty.
    fn sum_shares(shares: &[S]) -> Option<S>;
}
