[package]
name = "jester_algebra"
version = "0.1.0"
authors = ["Cydhra <ubezl@student.kit.edu>"]
edition = "2018"

[dependencies]
num = "0.2.0"
num-bigint = { version = "0.2.3", features = ["rand"] }
rand = "^0.7.2"
once_cell = "1.2.0"