[package]
name = "jester_double_ratchet"
version = "0.1.0"
authors = ["Cydhra <ubezl@student.kit.edu>"]
edition = "2018"

[dependencies]
jester_encryption = { path = "../jester_encryption" }
rand = "0.5.6"

[dev-dependencies]
jester_maths = { path = "../jester_maths"}